name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: flake8
      run: |
        flake8 src/ test/ 
    - name: pylint
      run: |
        pylint --fail-under=9.8 -d too-few-public-methods src/
        pylint --fail-under=9.8 -d missing-class-docstring,missing-function-docstring test/ 
    - name: tests
      run: |
        green -vv -r -l -m 99 -s 1 test
